### ISSUE TITLE
CSS issue

### ISSUE THREAD

**Issue by cormierjimmy** [CiscoDevNet/finesse-sample-code#15] opened 2021-11-25 16:25 UTC
Hi,
In our lab with Finesse 12.5 and CUIC 12.5 (UCCE), we got this issue with CSS:
Refused to apply style from 'https://finesse.local:8445/gadgets/proxy?container=default&gadget=http%3A%2F%2Flocalhost%3A8082%2F3rdpartygadget%2Ffiles%2FTEST_TELEPHONIE%2FCUIC.xml&debug=0&nocache=0&refresh=86400&html_tag_context=link&url=http%3A%2F%2Flocalhost%3A8082%2F3rdpartygadget%2Ffiles%2FTEST_TELEPHONIE%2FCUIC.css&code=e8720f016741d5c87eac0fc35845bb58bbba77b6' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

CSS file has not been edited from default
```
/**
 * Default attributes for gadget body.
 */
body {
    background: none transparent;
    padding: 0px;
}
#frame1 {
	width:100%;
	height:650;
}
#agentout {
	margin:4x;
}
```

XML file has not been edited except the url
```
![CDATA[
	<!-- Styling -->
    <link rel="stylesheet" href="CUIC.css" type="text/css" />


Our workaround is to set the value in cuic.js (html += '<iframe src="' + permalink + ' " width="100%" height="**650**" id="frame1" ></iframe>';)
```

**Comment by dekwan** [comment] 2021-12-01 18:58
Hi,

I attempted to reproduce this issue but was not able to. 

Also, as per the requirements for the CUICSampleGadget, this states that "You must be using CUIC 11.6(1) or below.", so although it may work with 12.5, it is not supported for this sample gadget.

Lastly, make sure the & sign in the permalink url was changed to &amp;

I am closing this issue since it was not reproducible and is using a version that is not supported.

**Closed as completed by dekwan** 2021-12-01 18:58 UTC
